# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_features_cpp <- function(senders, receivers, times, stat_names) {
    .Call(`_amore_compute_features_cpp`, senders, receivers, times, stat_names)
}

cpp_supported_stats <- function() {
    .Call(`_amore_cpp_supported_stats`)
}

